platform :ios, '16.0'

def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  use_frameworks!
  pod 'TensorFlowLiteSwift'
  pod 'MLKitObjectDetection'
  pod 'MLKitTextRecognition', '7.0.0'
end

target 'PluginTests' do
  capacitor_pods
  use_frameworks!
  pod 'TensorFlowLiteSwift'
  pod 'MLKitObjectDetection'
  pod 'MLKitTextRecognition', '7.0.0'
end
